name: Lint & Unit Test
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [dev]

jobs:
  check:
    uses: ./.github/workflows/lint-test.yml
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
