name: Lint & Unit Test
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/lint-test.yml
    permissions:
      contents: read
    secrets:
      inherit
